name: Check compile

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check-compile-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Check if project compiles
        run: bun run build

  check-compile-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Check if project compiles
        run: bun run build

  check-compile-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Check if project compiles
        run: bun run build
